#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=piv-deploy \
--device /dev/ttyACM0 \
-v "$(pwd)":/usr/src/app \
-v "$(pwd)/../configuration/:/configuration" \
-v "/pivdata/:/piv" \
-p 5000:5000 \
louisross/piv-deploy:1.0 \
bash
